modLoader="javafml"
loaderVersion="[38,)"
license="BSD (3 clause)"

[[mods]]
modId="gbook"
version="${file.jarVersion}"
displayName="Guidebook"
description='''
Books that guide
'''
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Guidebook/master/update.json"
issueTrackerURL="https://github.com/gigaherz/Guidebook/issues"
displayURL="https://github.com/gigaherz/Guidebook"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="gigaherz"

[[dependencies.gbook]]
    modId="forge"
    mandatory=true
    versionRange="[38.0.15,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"