modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
updateJSONURL="https://raw.githubusercontent.com/gigaherz/Guidebook/master/update.json" #optional
issueTrackerURL="https://github.com/gigaherz/Guidebook/issues" #optional
displayURL="https://github.com/gigaherz/Guidebook" #optional
logoFile="logo.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="gigaherz" #optional
license="BSD (3 clause)"

[[mods]] #mandatory
modId="gbook" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Guidebook" #mandatory
description='''
Books that guide
'''

[[dependencies.gbook]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.gbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,1.17)"
    ordering="NONE"
    side="BOTH"